name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install

      - name: eslint
        run: npm run eslint

      - name: prettier
        run: npm run prettier
